# Generated by Django 5.2.3 on 2025-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t1_researcharticle',
            old_name='co_authors',
            new_name='external_authors',
        ),
        migrations.RenameField(
            model_name='t1_researcharticle',
            old_name='indexing',
            new_name='indexing_other',
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='indexing_scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='indexing_ugc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='indexing_wos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='internal_authors',
            field=models.TextField(blank=True),
        ),
    ]
