# Generated by Django 5.2.3 on 2025-07-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0002_rename_co_authors_t1_researcharticle_external_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_researcharticle',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='author_type',
            field=models.CharField(choices=[('Sole', 'Sole'), ('First', 'First'), ('Corresponding', 'Corresponding'), ('Other', 'Other')], default='Sole', max_length=20),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='doi',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='faculty_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='google_drive_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='page_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='publication_month_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='t1_researcharticle',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
