# Generated by Django 5.2.3 on 2025-07-17 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0003_remove_t1_researcharticle_publication_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T1_2ResearchArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('Sole', 'Sole'), ('First', 'First'), ('Corresponding', 'Corresponding'), ('Other', 'Other')], default='Sole', max_length=20)),
                ('internal_authors', models.TextField(blank=True)),
                ('external_authors', models.TextField(blank=True)),
                ('conference_details', models.TextField(blank=True, help_text='Organization/Institution name, Place, State')),
                ('isbn_issn', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('page_no', models.CharField(blank=True, max_length=50)),
                ('publication_month_year', models.CharField(blank=True, max_length=20)),
                ('indexing_scopus', models.BooleanField(default=False)),
                ('indexing_other', models.CharField(blank=True, max_length=100)),
                ('conference_status', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='National', max_length=20)),
                ('conference_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('registration_fee_reimbursed', models.BooleanField(default=False, help_text='Was registration fee reimbursed by the college?')),
                ('special_leave_dates', models.CharField(blank=True, max_length=100)),
                ('certificate_link', models.URLField(blank=True, help_text='Google Drive link to certificate')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
