# Generated by Django 5.2.3 on 2025-07-18 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0005_t2_1workshopattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T2_2WorkshopOrganized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Co-Coordinator', 'Co-Coordinator')], default='Coordinator', max_length=50)),
                ('activity_type', models.CharField(help_text='FDP/Workshop/STTP etc.', max_length=100)),
                ('program_name', models.CharField(max_length=255)),
                ('organized_by_dept', models.CharField(help_text='Department', max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_days', models.PositiveIntegerField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10)),
                ('num_participants', models.PositiveIntegerField()),
                ('collaborator', models.CharField(blank=True, max_length=255)),
                ('report_link', models.URLField(blank=True)),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
