# Generated by Django 5.2.3 on 2025-07-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0008_t3_2chapterpublication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T4_1EditorialBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Title of the Book or Journal', max_length=255)),
                ('role', models.CharField(choices=[('Editor', 'Editor'), ('Co-editor', 'Co-editor'), ('Member', 'Member')], max_length=20)),
                ('publisher', models.CharField(help_text='Publisher with complete address', max_length=255)),
                ('issn_isbn', models.CharField(max_length=50, verbose_name='ISSN/ISBN No.')),
                ('indexing', models.CharField(choices=[('WoS', 'WoS'), ('Scopus', 'Scopus'), ('UGC CARE', 'UGC CARE'), ('Others', 'Others')], max_length=20)),
                ('year', models.PositiveIntegerField(verbose_name='Year (w.e.f.)')),
                ('type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=20, verbose_name='Type of Book/Journal')),
                ('proof_link', models.URLField(blank=True, verbose_name='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
