# Generated by Django 5.2.3 on 2025-07-20 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0010_t4_2reviewerdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T4_3CommitteeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('body_details', models.CharField(help_text='Details of the body/committee', max_length=255)),
                ('responsibility', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Member', 'Member')], max_length=20)),
                ('level', models.CharField(choices=[('University', 'University'), ('State', 'State'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('other_details', models.TextField(blank=True, help_text='Any other details')),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
