# Generated by Django 5.2.3 on 2025-07-20 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0011_t4_3committeemembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T5_1PatentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('internal_co_inventors', models.TextField(blank=True, help_text='Internal Co-Inventors')),
                ('external_co_inventors', models.TextField(blank=True, help_text='External Co-Inventors')),
                ('ipr_type', models.CharField(choices=[('Utility', 'Utility'), ('Process', 'Process'), ('Design', 'Design'), ('Copyright', 'Copyright'), ('Trademark', 'Trademark'), ('Other', 'Other')], max_length=20, verbose_name='Type of IPR')),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Filed', 'Filed'), ('Published', 'Published'), ('Granted', 'Granted')], max_length=20)),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('published_granted_date', models.DateField(blank=True, null=True)),
                ('publication_number', models.CharField(blank=True, help_text='Publication/Granted Number', max_length=100)),
                ('technology_transfer', models.BooleanField(default=False, help_text='Technology Transfer Applicable')),
                ('country', models.CharField(blank=True, help_text='Country of Patent', max_length=100)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
