# Generated by Django 5.2.3 on 2025-07-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0013_t5_2sponsoredproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T5_3ConsultancyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_faculty', models.TextField(blank=True, help_text='Internal Faculty Details')),
                ('external_faculty', models.TextField(blank=True, help_text='External Faculty Details')),
                ('client_name', models.CharField(help_text='Name of Client', max_length=255)),
                ('title', models.CharField(help_text='Title of Consultancy', max_length=255)),
                ('sanctioned_order_no', models.CharField(blank=True, max_length=100)),
                ('sanctioned_date', models.DateField(blank=True, null=True)),
                ('sanctioned_amount_lakhs', models.DecimalField(decimal_places=2, help_text='In Lakhs', max_digits=12)),
                ('amount_received_rupees', models.DecimalField(decimal_places=2, help_text='In Rupees', max_digits=15)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('duration', models.CharField(choices=[('Short-Term', 'Short-Term'), ('Medium-Term', 'Medium-Term'), ('Long-Term', 'Long-Term'), ('Other', 'Other')], max_length=50)),
                ('regionality', models.CharField(choices=[('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
