# Generated by Django 5.2.3 on 2025-07-20 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0016_t5_5labequipmentdevelopment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T5_6ResearchGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Co-Supervisor', 'Co-Supervisor')], max_length=20)),
                ('candidate_name', models.CharField(help_text='Name of Candidate', max_length=200)),
                ('enrollment_number', models.CharField(help_text='Enrollment No.', max_length=100)),
                ('thesis_title', models.CharField(help_text='Title of Thesis', max_length=255)),
                ('registration_date', models.DateField(help_text='Date of Registration')),
                ('viva_voce_date', models.DateField(help_text='Date of PhD Viva-Voce')),
                ('external_examiner_details', models.TextField(help_text='Complete Details of External Examiner')),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('research_center', models.CharField(help_text='Name of the Research Center', max_length=255)),
                ('conferring_university', models.CharField(help_text='Name of the PhD Conferring University', max_length=255)),
                ('proof_link', models.URLField(blank=True, help_text='Drive Link: For Ongoing → RDC Letter; for Completed → Notification Letter')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
