# Generated by Django 5.2.3 on 2025-07-21 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0019_t6_2professionalbodymembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T6_3Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=200)),
                ('award_name', models.CharField(help_text='Name of Award', max_length=255)),
                ('conferred_by', models.CharField(help_text='Award Conferred by', max_length=255)),
                ('award_date', models.DateField(help_text='Award Date')),
                ('award_type', models.CharField(choices=[('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
