# Generated by Django 5.2.3 on 2025-07-21 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0020_t6_3award'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T6_4ResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Name of Faculty', max_length=200)),
                ('invited_by', models.CharField(help_text='Invited By', max_length=255)),
                ('lecture_title', models.CharField(help_text='Title/Subject of Lecture Delivered', max_length=255)),
                ('date', models.DateField(help_text='Date of Lecture')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
