# Generated by Django 5.2.3 on 2025-07-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0021_t6_4resourceperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T6_5AICTEInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(help_text='Name of Faculty', max_length=200)),
                ('initiative_name', models.CharField(help_text='Name of the AICTE Initiative Taken (e.g. Clean & Smart Campus, Smart India Hackathon, Unnat Bharat Abhiyan, Blood Donation, etc.)', max_length=500)),
                ('date', models.DateField(help_text='Date of Initiative (DD/MMM/YYYY)')),
                ('role', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Member', 'Member'), ('Participant', 'Participant'), ('Other', 'Other')], max_length=20)),
                ('organizing_institute', models.CharField(help_text='Name of the Organizing Institute', max_length=255)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
