# Generated by Django 5.2.3 on 2025-07-21 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0022_t6_5aicteinitiative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T7_1ProgramOrganized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(help_text='Name of the Organizer (Club/Professional Body)', max_length=255)),
                ('event_name', models.CharField(help_text='Name of the Event/Competition', max_length=255)),
                ('event_type', models.CharField(help_text='Type of Event/Competition', max_length=255)),
                ('start_date', models.DateField(help_text='Program Start Date (DD/MMM/YYYY)')),
                ('end_date', models.DateField(help_text='Program End Date (DD/MMM/YYYY)')),
                ('num_days', models.PositiveIntegerField(help_text='Number of Days')),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('participants_count', models.PositiveIntegerField(help_text='Number of Participants Attended')),
                ('collaborator_details', models.TextField(blank=True, help_text='Collaborator (if any) with contact details')),
                ('report_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Report)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
