# Generated by Django 5.2.3 on 2025-07-21 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0023_t7_1programorganized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S1_1TheorySubjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Semester (e.g. S1, S2…)', max_length=10)),
                ('name_of_subject', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=50)),
                ('faculty_name', models.CharField(help_text='Faculty who conducted the classes', max_length=200)),
                ('num_classes', models.PositiveIntegerField(help_text='No. of Classes Conducted')),
                ('num_students_appeared', models.PositiveIntegerField(help_text='No. of Students Appeared')),
                ('num_students_passed', models.PositiveIntegerField(help_text='No. of Students Passed')),
                ('pass_percent', models.DecimalField(decimal_places=2, help_text='% Pass in the Subject', max_digits=5)),
                ('pass_percent_rv', models.DecimalField(decimal_places=2, help_text='% Pass after RV/RRV', max_digits=5)),
                ('prev_year_pass_percent', models.DecimalField(decimal_places=2, help_text='Previous Year % Result', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
