# Generated by Django 5.2.3 on 2025-07-21 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0024_s1_1theorysubjectdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S2_1StudentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('Sole', 'Sole'), ('First', 'First'), ('Corresponding', 'Corresponding'), ('Other', 'Other')], max_length=20)),
                ('internal_authors', models.TextField(help_text='Internal Authors')),
                ('external_authors', models.TextField(help_text='External Authors')),
                ('journal_name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=50)),
                ('issue', models.CharField(blank=True, max_length=50)),
                ('page_numbers', models.CharField(blank=True, max_length=100)),
                ('month_year', models.CharField(help_text='Month & Year of Publication', max_length=50)),
                ('issn_number', models.CharField(blank=True, max_length=50, verbose_name='ISSN Number')),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Impact Factor', max_digits=5, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('is_wos', models.BooleanField(default=False, help_text='Web of Science')),
                ('is_scopus', models.BooleanField(default=False)),
                ('is_ugc_care', models.BooleanField(default=False, help_text='UGC CARE')),
                ('other_indexing', models.CharField(blank=True, help_text='Other (Referred Journal)', max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
