# Generated by Django 5.2.3 on 2025-07-21 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0025_s2_1studentarticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S2_2StudentConferencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('Sole', 'Sole'), ('First', 'First'), ('Corresponding', 'Corresponding'), ('Other', 'Other')], max_length=20)),
                ('internal_authors', models.TextField(help_text='Internal Authors')),
                ('external_authors', models.TextField(help_text='External Authors')),
                ('conference_details', models.CharField(help_text='Organization/Institution name, Place, State', max_length=255)),
                ('isbn_issn', models.CharField(blank=True, max_length=50, verbose_name='ISBN/ISSN')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('page_numbers', models.CharField(blank=True, help_text='Page No', max_length=100)),
                ('month_year', models.CharField(help_text='Month & Year', max_length=50)),
                ('is_scopus', models.BooleanField(default=False, help_text='Scopus Indexed')),
                ('other_indexing', models.CharField(blank=True, help_text='Other Indexing (Referred Journal)', max_length=255)),
                ('conference_status', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=20)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
