# Generated by Django 5.2.3 on 2025-07-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0026_s2_2studentconferencepaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S2_3StudentSponsoredProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('semester', models.CharField(help_text='Semester (e.g. S1, S2…)', max_length=10)),
                ('project_title', models.CharField(help_text='Title of the Project', max_length=255)),
                ('sponsored_by', models.CharField(help_text='Sponsored By', max_length=255)),
                ('guide_name', models.CharField(help_text='Name of the Guide', max_length=200)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
