# Generated by Django 5.2.3 on 2025-07-21 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0027_s2_3studentsponsoredproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S3_1CompetitionParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('semester', models.CharField(help_text='Semester (e.g. S1, S2…)', max_length=10)),
                ('activity_type', models.CharField(help_text='Type of Activity (Sports/Cultural etc.)', max_length=255)),
                ('organized_by', models.CharField(help_text='Organized By', max_length=255)),
                ('date', models.DateField(help_text='Date of Participation')),
                ('level', models.CharField(choices=[('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('awards', models.CharField(blank=True, help_text='Awards (if any)', max_length=255)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
