# Generated by Django 5.2.3 on 2025-07-21 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0028_s3_1competitionparticipation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S3_2DeptProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(help_text='Name of the Programme/Competition', max_length=255)),
                ('participants_count', models.PositiveIntegerField(help_text='Number of Participants')),
                ('program_type', models.CharField(help_text='Type of Programme/Competition', max_length=255)),
                ('external_agency', models.CharField(blank=True, help_text='In collaboration with external agency (if any)', max_length=255)),
                ('date', models.DateField(help_text='Date of Programme')),
                ('level', models.CharField(choices=[('Regional', 'Regional'), ('National', 'National'), ('International', 'International')], max_length=20)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
