# Generated by Django 5.2.3 on 2025-07-21 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0029_s3_2deptprogram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S4_1StudentExamQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('batch', models.CharField(help_text='Batch (e.g. 2024)', max_length=50)),
                ('exam_name', models.CharField(help_text='Competitive Exam Qualified (GATE/CAT/GRE/GMAT etc.)', max_length=255)),
                ('registration_number', models.CharField(help_text='Registration/Roll Number', max_length=100)),
                ('score_detail', models.CharField(help_text='AIR/Percentile/Score', max_length=100)),
                ('pg_programme', models.CharField(help_text='PG Programme Admitted (M.Tech/MS/MBA etc.)', max_length=100)),
                ('admission_year', models.PositiveIntegerField(help_text='Year of Admission in Higher Studies')),
                ('institution_name', models.CharField(help_text='Institution Joined', max_length=255)),
                ('contact_details', models.CharField(help_text='Contact Details', max_length=255)),
                ('email', models.EmailField(help_text='E-mail ID', max_length=254)),
                ('mobile', models.CharField(help_text='Mobile No.', max_length=15)),
                ('social_profile_link', models.URLField(blank=True, help_text='Profile in Social Sites (LinkedIn, Twitter etc.)')),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
