# Generated by Django 5.2.3 on 2025-07-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0030_s4_1studentexamqualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S4_2CampusRecruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('batch', models.CharField(help_text='Batch (e.g. 2024)', max_length=50)),
                ('company_name', models.CharField(help_text='Name of the Company Joined', max_length=255)),
                ('package_offered', models.DecimalField(decimal_places=2, help_text='Package Offered', max_digits=10)),
                ('offer_ref_number', models.CharField(help_text='Offer Letter Reference Number', max_length=100)),
                ('contact_details', models.CharField(help_text='Contact Details of Student', max_length=255)),
                ('email', models.EmailField(help_text='E-mail ID', max_length=254)),
                ('mobile', models.CharField(help_text='Mobile No.', max_length=15)),
                ('social_profile_link', models.URLField(blank=True, help_text='Profile in Social Sites (Facebook/LinkedIn/Twitter)')),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
