# Generated by Django 5.2.3 on 2025-07-21 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0032_s4_3govtpsuselection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S4_4PlacementHigherStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.CharField(help_text='Roll No.', max_length=50)),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('photo_link', models.URLField(blank=True, help_text='Photo URL')),
                ('placement_type', models.CharField(choices=[('Software', 'Software'), ('Core', 'Core'), ('PSU', 'PSU'), ('Other', 'Other')], help_text='Software/Core/PSU/Other', max_length=20)),
                ('organization_name', models.CharField(blank=True, help_text='Name of Organization (placement)', max_length=255)),
                ('package_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Package Offered', max_digits=10, null=True)),
                ('program_name', models.CharField(blank=True, help_text='Name of the Programme (higher studies)', max_length=255)),
                ('institution_joined', models.CharField(blank=True, help_text='Name of the Institution Joined', max_length=255)),
                ('admission_year', models.PositiveIntegerField(blank=True, help_text='Year of Admission', null=True)),
                ('entrepreneurship', models.CharField(blank=True, help_text='Name of Company (if student became entrepreneur)', max_length=255, verbose_name='Entrepreneurship (Company)')),
                ('email', models.EmailField(help_text='E-mail ID', max_length=254)),
                ('contact_details', models.CharField(help_text='Contact Details', max_length=255)),
                ('mobile', models.CharField(help_text='Mobile No.', max_length=15)),
                ('social_profile_link', models.URLField(blank=True, help_text='Profile in Social Sites (LinkedIn, Twitter etc.)')),
                ('offer_ref_number', models.CharField(blank=True, help_text='Reference Number of Joining Letter', max_length=100)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
