# Generated by Django 5.2.3 on 2025-07-21 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0033_s4_4placementhigherstudies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S5_1StudentCertificationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student', max_length=200)),
                ('certification_course', models.CharField(help_text='Name of the Certification Course', max_length=255)),
                ('category', models.CharField(help_text='Category of the Course (e.g. CSE, ECE, etc.)', max_length=255)),
                ('duration', models.CharField(help_text='Duration of the Course', max_length=100)),
                ('credit_points', models.CharField(help_text='Credit Points Earned', max_length=50)),
                ('certification_type', models.CharField(choices=[('Elite-Gold', 'Elite-Gold'), ('Elite-Silver', 'Elite-Silver'), ('Passed', 'Passed'), ('Other', 'Other')], help_text='Elite-Gold / Elite-Silver / Passed / Other', max_length=20)),
                ('certificate_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Certificate)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
