# Generated by Django 5.2.3 on 2025-07-21 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0035_s5_2vocationaltraining'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='S5_3SpecialMentionAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the Student/Alumni', max_length=200)),
                ('award_name', models.CharField(help_text='Name of the Award', max_length=255)),
                ('work_title', models.CharField(help_text='Name of the Work for which Award is received', max_length=255)),
                ('date_received', models.DateField(help_text='Date of Award Received')),
                ('awarding_organization', models.CharField(help_text='Name of Awarding Organization', max_length=255)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Award Amount (INR), if any', max_digits=12, null=True)),
                ('award_level', models.CharField(choices=[('University', 'University'), ('State', 'State'), ('National', 'National'), ('International', 'International')], help_text='Level of Award', max_length=20)),
                ('proof_link', models.URLField(blank=True, help_text='Google Drive Link (Upload Proof)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1_research.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
