# Generated by Django 5.2.3 on 2025-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0037_s5_4studententrepreneurship'),
    ]

    operations = [
        migrations.AddField(
            model_name='t4_1editorialboard',
            name='quarter',
            field=models.CharField(default='Q1', max_length=10),
        ),
    ]
