# Generated by Django 5.2.3 on 2025-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0038_t4_1editorialboard_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='t4_2reviewerdetails',
            name='quarter',
            field=models.CharField(default='Q1', max_length=10),
        ),
    ]
