# Generated by Django 5.2.3 on 2025-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1_research', '0039_t4_2reviewerdetails_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t6_5aicteinitiative',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
