# Generated by Django 5.2.3 on 2025-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t2_2workshoporganized',
            name='role',
            field=models.CharField(choices=[('Coordinator', 'Coordinator'), ('Co-Coordinator', 'Co-Coordinator')], default='Coordinator', max_length=50),
        ),
    ]
