# Generated by Django 5.2.3 on 2025-08-12 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_t2_2workshoporganized_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='s1_1theorysubjectdata',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s1_1theorysubjectdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s2_1studentarticle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s2_1studentarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s2_2studentconferencepaper',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s2_2studentconferencepaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s2_3studentsponsoredproject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s2_3studentsponsoredproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s3_1competitionparticipation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s3_1competitionparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s3_2deptprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s3_2deptprogram',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s4_1studentexamqualification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s4_1studentexamqualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s4_2campusrecruitment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s4_2campusrecruitment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s4_3govtpsuselection',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s4_3govtpsuselection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s4_4placementhigherstudies',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s4_4placementhigherstudies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s5_1studentcertificationcourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s5_1studentcertificationcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s5_2vocationaltraining',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s5_2vocationaltraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s5_3specialmentionachievement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s5_3specialmentionachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='s5_4studententrepreneurship',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='s5_4studententrepreneurship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t1_2researcharticle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t1_2researcharticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t1_researcharticle',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t1_researcharticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t2_1workshopattendance',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t2_1workshopattendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t2_2workshoporganized',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t2_2workshoporganized',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t3_1bookpublication',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t3_1bookpublication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t3_2chapterpublication',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t3_2chapterpublication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t4_1editorialboard',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t4_1editorialboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t4_2reviewerdetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t4_2reviewerdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t4_3committeemembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t4_3committeemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_1patentdetails',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_1patentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_2sponsoredproject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_2sponsoredproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_3consultancyproject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_3consultancyproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_4coursedevelopment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_4coursedevelopment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_5labequipmentdevelopment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_5labequipmentdevelopment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t5_6researchguidance',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t5_6researchguidance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t6_1certificationcourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t6_1certificationcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t6_2professionalbodymembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t6_2professionalbodymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t6_3award',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t6_3award',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t6_4resourceperson',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t6_4resourceperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t6_5aicteinitiative',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t6_5aicteinitiative',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='t7_1programorganized',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
        migrations.AlterField(
            model_name='t7_1programorganized',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
