// src/config/formConfig.jsx
import React from "react";
import * as fields from "./formFieldTemplates.jsx"; 


// --- DYNAMIC IMPORTS: Using React.lazy for performance ---
const T1_1Form = React.lazy(() => import("../components/T1_1Form"));
const T1_2Form = React.lazy(() => import("../components/T1_2Form"));
const T2_1Form = React.lazy(() => import("../components/T2_1Form"));
const T2_2Form = React.lazy(() => import("../components/T2_2Form"));
const T3_1Form = React.lazy(() => import("../components/T3_1Form"));
const T3_2Form = React.lazy(() => import("../components/T3_2Form"));
const T4_1Form = React.lazy(() => import("../components/T4_1Form"));
const T4_2Form = React.lazy(() => import("../components/T4_2Form"));
const T4_3Form = React.lazy(() => import("../components/T4_3Form"));
const T5_1Form = React.lazy(() => import("../components/T5_1Form"));
const T5_2Form = React.lazy(() => import("../components/T5_2Form"));
const T5_3Form = React.lazy(() => import("../components/T5_3Form"));
const T5_4Form = React.lazy(() => import("../components/T5_4Form"));
const T5_5Form = React.lazy(() => import("../components/T5_5Form"));
const T5_6Form = React.lazy(() => import("../components/T5_6Form"));
const T6_1Form = React.lazy(() => import("../components/T6_1Form"));
const T6_2Form = React.lazy(() => import("../components/T6_2Form"));
const T6_3Form = React.lazy(() => import("../components/T6_3Form"));
const T6_4Form = React.lazy(() => import("../components/T6_4Form"));
const T6_5Form = React.lazy(() => import("../components/T6_5Form"));
const T7_1Form = React.lazy(() => import("../components/T7_1Form"));
const S1_1Form = React.lazy(() => import("../components/S1_1Form"));
const S2_1Form = React.lazy(() => import("../components/S2_1Form"));
const S2_2Form = React.lazy(() => import("../components/S2_2Form"));
const S2_3Form = React.lazy(() => import("../components/S2_3Form"));
const S3_1Form = React.lazy(() => import("../components/S3_1Form"));
const S3_2Form = React.lazy(() => import("../components/S3_2Form"));
const S4_1Form = React.lazy(() => import("../components/S4_1Form"));
const S4_2Form = React.lazy(() => import("../components/S4_2Form"));
const S4_3Form = React.lazy(() => import("../components/S4_3Form"));
const S4_4Form = React.lazy(() => import("../components/S4_4Form"));
const S5_1Form = React.lazy(() => import("../components/S5_1Form"));
const S5_2Form = React.lazy(() => import("../components/S5_2Form"));
const S5_3Form = React.lazy(() => import("../components/S5_3Form"));
const S5_4Form = React.lazy(() => import("../components/S5_4Form"));

export const formSections = [
  { code: "T1.1", title: "T1.1: Details of the Published Research Articles/Papers in Journals/Periodicals" },
  { code: "T1.2", title: "T1.2: Details of the Paper Publication in Conferences" },
  { code: "T2.1", title: "Details of the FDP/Short Term Training Program/Workshop etc. Attended By Faculty Members" },
  { code: "T2.2", title: "Details of FDP/STTP/Workshop/Skill Development Organized" },
  { code: "T3.1", title: "Consultancy Details of Books/Monographs Published" },
  { code: "T3.2", title: "Details of Chapters Published in Books/Reference Books/Edited Books" },
  { code: "T4.1", title: "Funded Research Projects (New)" },
  { code: "T4.2", title: "Funded Research Projects (Ongoing)" },
  { code: "T4.3", title: "Research Guidance: Ph.D. Awarded" },
  { code: "T5.1", title: "Conferences / Seminars / Workshops Conducted" },
  { code: "T5.2", title: "FDPs / STTPs Conducted" },
  { code: "T5.3", title: "FDPs / STTPs Attended" },
  { code: "T5.4", title: "Invited Talks / Guest Lectures Delivered" },
  { code: "T5.5", title: "Chair / Co-chair / Panelist Roles" },
  { code: "T5.6", title: "MOUs Signed" },
  { code: "T6.1", title: "National / International Awards / Recognitions" },
  { code: "T6.2", title: "Professional Society Memberships" },
  { code: "T6.3", title: "Reviewers / Editorial Board Members" },
  { code: "T6.4", title: "Students Qualified GATE/NET/GMAT/etc." },
  { code: "T6.5", title: "Hackathons / Technical Competitions" },
  { code: "T7.1", title: "Startups / Entrepreneurship Initiatives" },
  { code: "S1.1", title: "S1.1: Theory Subject Data" },
  { code: "S2.1", title: "Details of the Published Research Articles/Papers in Journals/Periodicals by the students" },
  { code: "S2.2", title: "Details of the Research Paper Presented by the Students in a conferences" },
  { code: "S2.3", title: "Details of Sponsored/Collaboration with industry Projects Carried Out By Students as a Part of Their Curriculum" },
  { code: "S3.1", title: "S3.1: Details of the Competitions Organized/Participation by the Students" },
  { code: "S3.2", title: "S3.2: Details of the Programme Organized by the Department for the Students" },
  { code: "S4.1", title: "S4.1: Details of the Students Qualified GATE" },
  { code: "S4.2", title: "S4.2: Details of the Students selected in Campus Recruitment" },
  { code: "S4.3", title: "S4.3: Details of the Students selected in Government/Public Sector Units" },
  { code: "S4.4", title: "S4.4: Complete Details of the Students selected in Companies and Higher Studies" },
  { code: "S5.1", title: "S5.1: Details of Certification Courses completed by the Students" },
  { code: "S5.2", title: "S5.2: Details of the vocational training/workshop/industrial visit" },
  { code: "S5.3", title: "S5.3: Details of Special Mention achievements/Awards Received" },
  { code: "S5.4", title: "S5.4: Details of students established as Entrepreneurs" },
];

export const formConfig = {
  "T1.1": {
    endpoint: "api/data/t1research/",
    modelName: "T1_ResearchArticle",
    FormComponent: T1_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Title", key: "title" },
      { label: "Journal Name", key: "journal_name" },
      ...fields.authorFields,
      ...fields.publicationFields,
      { label: "ISSN Number", key: "issn_number" },
      { label: "Impact Factor", key: "impact_factor" },
      { label: "WOS Indexed", key: "indexing_wos", render: fields.renderBoolean("indexing_wos") },
      { label: "Scopus Indexed", key: "indexing_scopus", render: fields.renderBoolean("indexing_scopus") },
      { label: "UGC Care", key: "indexing_ugc", render: fields.renderBoolean("indexing_ugc") },
      { label: "Other Indexing", key: "indexing_other" },
      { label: "DOI", key: "doi" },
      { label: "Document Link", key: "google_drive_link", render: fields.renderLink("google_drive_link") },
      fields.departmentNameField,
    ],
  },
  "T1.2": {
    endpoint: "api/data/t1_2research/",
    modelName: "T1_2ResearchArticle",
    FormComponent: T1_2Form,
    listFields: [
      fields.facultyNameField,
      { label: "Title", key: "title" },
      ...fields.authorFields,
      { label: "Conference Details", key: "conference_details" },
      { label: "ISBN/ISSN", key: "isbn_issn" },
      ...fields.publicationFields,
      ...fields.indexingFields,
      ...fields.conferenceFields,
      { label: "Fee Reimbursed", key: "registration_fee_reimbursed", render: fields.renderBoolean("registration_fee_reimbursed") },
      { label: "Special Leave Dates", key: "special_leave_dates" },
      fields.certificateLinkField,
      fields.departmentNameField,
      ...fields.sessionFields,
    ],
  },
  "T2.1": {
    endpoint: "api/data/t2_1workshops/",
    modelName: "T2_1WorkshopAttendance",
    FormComponent: T2_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Program Name", key: "program_name" },
      { label: "Organizer", key: "organizer" },
      { label: "Place", key: "place" },
      { label: "Start Date", key: "start_date" },
      { label: "End Date", key: "end_date" },
      { label: "Days", key: "num_days" },
      { label: "Mode", key: "mode" },
      { label: "Fee Reimbursed", key: "registration_fee_reimbursed", render: fields.renderBoolean("registration_fee_reimbursed") },
      { label: "Special Leave Dates", key: "special_leave_dates" },
      fields.certificateLinkField,
      fields.departmentNameField,
      ...fields.sessionFields,
    ],
  },
  "T2.2": {
    endpoint: "api/data/t2_2organized/",
    modelName: "T2_2WorkshopOrganized",
    FormComponent: T2_2Form,
    listFields: [
      fields.facultyNameField,
      { label: "Role", key: "role" },
      { label: "Activity Type", key: "activity_type" },
      { label: "Program Name", key: "program_name" },
      { label: "Organized By (Dept)", key: "organized_by_dept" },
      { label: "Start Date", key: "start_date" },
      { label: "End Date", key: "end_date" },
      { label: "Days", key: "num_days" },
      { label: "Mode", key: "mode" },
      { label: "Participants", key: "num_participants" },
      { label: "Collaborator", key: "collaborator" },
      fields.reportLinkField,
      fields.departmentNameField,
      ...fields.sessionFields,
    ],
  },
  "T3.1": {
    endpoint: "api/data/t3_1books/",
    modelName: "T3_1BookPublication",
    FormComponent: T3_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Book Title", key: "book_title" },
      { label: "Author Type", key: "author_type" },
      { label: "Publisher", key: "publisher_details" },
      { label: "ISBN/ISSN", key: "isbn_number" },
      { label: "Indexing", key: "indexing" },
      { label: "Publication Year", key: "publication_year" },
      { label: "Print Mode", key: "print_mode" },
      { label: "Book Type", key: "book_type" },
      fields.proofLinkField,
      fields.departmentNameField,
      ...fields.sessionFields,
    ],
  },
  "T3.2": {
    endpoint: "api/data/t3_2chapters/",
    modelName: "T3_2ChapterPublication",
    FormComponent: T3_2Form,
    listFields: [
      fields.facultyNameField,
      { label: "Chapter Title", key: "chapter_title" },
      { label: "Author Type", key: "author_type" },
      { label: "Publisher", key: "publisher_details" },
      { label: "ISBN/ISSN", key: "isbn_number" },
      { label: "Indexing", key: "indexing" },
      { label: "Publication Year", key: "publication_year" },
      { label: "Book Type", key: "book_type" },
      fields.proofLinkField,
      fields.departmentNameField,
      ...fields.sessionFields,
    ],
  },
  "T4.1": {
    endpoint: "api/data/t4_1editorial/",
    modelName: "T4_1EditorialBoard",
    FormComponent: T4_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Title", key: "title" },
      { label: "Role", key: "role" },
      { label: "Publisher", key: "publisher" },
      { label: "ISSN/ISBN", key: "issn_isbn" },
      { label: "Indexing", key: "indexing" },
      { label: "Type", key: "type" },
      fields.proofLinkField,
      ...fields.sessionFields,
    ],
  },
  "T4.2": {
    endpoint: "api/data/t4_2reviewers/",
    modelName: "T4_2ReviewerDetails",
    FormComponent: T4_2Form,
    listFields: [
      fields.facultyNameField,
      { label: "Publication Type", key: "publication_type" },
      { label: "Title", key: "title" },
      { label: "Indexing", key: "indexing" },
      fields.proofLinkField,
      ...fields.sessionFields,
    ],
  },
  "T4.3": {
    endpoint: "api/data/t4_3committees/",
    modelName: "T4_3CommitteeMembership",
    FormComponent: T4_3Form,
    listFields: [
      fields.facultyNameField,
      { label: "Committee", key: "body_details" },
      { label: "Responsibility", key: "responsibility" },
      { label: "Level", key: "level" },
      fields.proofLinkField,
      ...fields.sessionFields,
    ],
  },
  "T5.1": {
    endpoint: "api/data/t5_1patents/",
    modelName: "T5_1PatentDetails",
    FormComponent: T5_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Title", key: "title" },
      { label: "Co-Inventors (Internal)", key: "internal_co_inventors" },
      { label: "Co-Inventors (External)", key: "external_co_inventors" },
      { label: "IPR Type", key: "ipr_type" },
      { label: "Application No", key: "application_number" },
      { label: "Status", key: "status" },
      { label: "Filled Date", key: "filled_date" },
      { label: "Published/Granted Date", key: "published_granted_date" },
      { label: "Tech Transfer", key: "technology_transfer", render: fields.renderBoolean("technology_transfer") },
      { label: "Country", key: "country" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T5.2": {
    endpoint: "api/data/t5_2sponsored/",
    modelName: "T5_2SponsoredProject",
    FormComponent: T5_2Form,
    listFields: [
      { label: "PI", key: "principal_investigator" },
      { label: "Co-PI", key: "co_principal_investigator" },
      { label: "Funding Agency", key: "funding_agency" },
      { label: "Project Title", key: "project_title" },
      { label: "Status", key: "status" },
      { label: "Amount (Lakhs)", key: "sanctioned_amount_lakhs" },
      { label: "Duration", key: "duration" },
      { label: "Regionality", key: "regionality" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T5.3": {
    endpoint: "api/data/t5_3consultancy/",
    modelName: "T5_3ConsultancyProject",
    FormComponent: T5_3Form,
    listFields: [
      { label: "Internal Faculty", key: "internal_faculty" },
      { label: "Client Name", key: "client_name" },
      { label: "Title", key: "title" },
      { label: "Amount (Lakhs)", key: "sanctioned_amount_lakhs" },
      { label: "Status", key: "status" },
      { label: "Duration", key: "duration" },
      { label: "Regionality", key: "regionality" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T5.4": {
    endpoint: "api/data/t5_4content/",
    modelName: "T5_4CourseDevelopment",
    FormComponent: T5_4Form,
    listFields: [
      fields.facultyNameField,
      { label: "Course/Module Name", key: "course_module_name" },
      { label: "Platform", key: "platform" },
      { label: "Launch Date", key: "launch_date" },
      { label: "Link", key: "link", render: fields.renderLink("link") },
      fields.departmentNameField,
    ],
  },
  "T5.5": {
    endpoint: "api/data/t5_5labequipment/",
    modelName: "T5_5LabEquipmentDevelopment",
    FormComponent: T5_5Form,
    listFields: [
      { label: "Lab Name", key: "lab_name" },
      { label: "Major Equipment", key: "major_equipment" },
      { label: "Purpose", key: "purpose" },
      { label: "Cost", key: "equipment_cost" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T5.6": {
    endpoint: "api/data/t5_6research/",
    modelName: "T5_6ResearchGuidance",
    FormComponent: T5_6Form,
    listFields: [
      fields.facultyNameField,
      { label: "Role", key: "role" },
      { label: "Candidate Name", key: "candidate_name" },
      { label: "Thesis Title", key: "thesis_title" },
      { label: "Status", key: "status" },
      { label: "University", key: "conferring_university" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T6.1": {
    endpoint: "api/data/t6_1certcourses/",
    modelName: "T6_1CertificationCourse",
    FormComponent: T6_1Form,
    listFields: [
      fields.facultyNameField,
      { label: "Certification Course", key: "certification_course" },
      { label: "Course Name", key: "course_name" },
      { label: "Duration", key: "duration" },
      { label: "Type", key: "certification_type" },
      fields.certificateLinkField,
      fields.departmentNameField,
    ],
  },
  "T6.2": {
    endpoint: "api/data/t6_2professmb/",
    modelName: "T6_2ProfessionalBodyMembership",
    FormComponent: T6_2Form,
    listFields: [
      fields.facultyNameField,
      { label: "Institution", key: "institution_name" },
      { label: "Grade", key: "membership_grade" },
      { label: "Membership No.", key: "membership_number" },
      { label: "Year of Election", key: "year_of_election" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T6.3": {
    endpoint: "api/data/t6_3awards/",
    modelName: "T6_3Award",
    FormComponent: T6_3Form,
    listFields: [
      fields.facultyNameField,
      { label: "Award Name", key: "award_name" },
      { label: "Conferred By", key: "conferred_by" },
      { label: "Date", key: "award_date" },
      { label: "Type", key: "award_type" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T6.4": {
    endpoint: "api/data/t6_4resource/",
    modelName: "T6_4ResourcePerson",
    FormComponent: T6_4Form,
    listFields: [
      fields.facultyNameField,
      { label: "Invited By", key: "invited_by" },
      { label: "Lecture Title", key: "lecture_title" },
      { label: "Date", key: "date" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T6.5": {
    endpoint: "api/data/t6_5aicte/",
    modelName: "T6_5AICTEInitiative",
    FormComponent: T6_5Form,
    listFields: [
      fields.facultyNameField,
      { label: "Initiative Name", key: "initiative_name" },
      { label: "Date", key: "date" },
      { label: "Role", key: "role" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "T7.1": {
    endpoint: "api/data/t7_1programs/",
    modelName: "T7_1ProgramOrganized",
    FormComponent: T7_1Form,
    listFields: [
      { label: "Organizer", key: "organizer_name" },
      { label: "Event Name", key: "event_name" },
      { label: "Event Type", key: "event_type" },
      { label: "Start Date", key: "start_date" },
      { label: "Participants", key: "participants_count" },
      fields.reportLinkField,
    ],
  },
  "S1.1": {
    endpoint: "api/data/s1_1subjects/",
    modelName: "S1_1TheorySubjectData",
    FormComponent: S1_1Form,
    listFields: [
      { label: "Subject", key: "name_of_subject" },
      { label: "Subject Code", key: "subject_code" },
      { label: "Faculty", key: "faculty_name" },
      { label: "Pass %", key: "pass_percent" },
      ...fields.sessionFields,
    ],
  },
  "S2.1": {
    endpoint: "api/data/s2_1articles/",
    modelName: "S2_1StudentArticle",
    FormComponent: S2_1Form,
    listFields: [
      { label: "Title", key: "title" },
      { label: "Journal Name", key: "journal_name" },
      ...fields.authorFields,
      ...fields.publicationFields,
      ...fields.indexingFields,
      fields.proofLinkField,
    ],
  },
  "S2.2": {
    endpoint: "api/data/s2_2conferences/",
    modelName: "S2_2StudentConferencePaper",
    FormComponent: S2_2Form,
    listFields: [
      { label: "Title", key: "title" },
      ...fields.authorFields,
      { label: "Conference Details", key: "conference_details" },
      ...fields.conferenceFields,
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S2.3": {
    endpoint: "api/data/s2_3sponsored/",
    modelName: "S2_3StudentSponsoredProject",
    FormComponent: S2_3Form,
    listFields: [
      fields.studentNameField,
      { label: "Semester", key: "semester" },
      { label: "Project Title", key: "project_title" },
      { label: "Sponsored By", key: "sponsored_by" },
      { label: "Guide Name", key: "guide_name" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S3.1": {
    endpoint: "api/data/s3_1competitions/",
    modelName: "S3_1CompetitionParticipation",
    FormComponent: S3_1Form,
    listFields: [
      fields.studentNameField,
      { label: "Activity Type", key: "activity_type" },
      { label: "Organized By", key: "organized_by" },
      { label: "Level", key: "level" },
      { label: "Awards", key: "awards" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S3.2": {
    endpoint: "api/data/s3_2deptprograms/",
    modelName: "S3_2DeptProgram",
    FormComponent: S3_2Form,
    listFields: [
      { label: "Program Name", key: "program_name" },
      { label: "Participants", key: "participants_count" },
      { label: "Program Type", key: "program_type" },
      { label: "Level", key: "level" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S4.1": {
    endpoint: "api/data/s4_1examqual/",
    modelName: "S4_1StudentExamQualification",
    FormComponent: S4_1Form,
    listFields: [
      fields.studentNameField,
      { label: "Exam Name", key: "exam_name" },
      { label: "Score", key: "score_detail" },
      { label: "Institution Joined", key: "institution_name" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S4.2": {
    endpoint: "api/data/s4_2campus/",
    modelName: "S4_2CampusRecruitment",
    FormComponent: S4_2Form,
    listFields: [
      fields.studentNameField,
      { label: "Company Name", key: "company_name" },
      { label: "Package", key: "package_offered" },
      fields.socialProfileLinkField,
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S4.3": {
    endpoint: "api/data/s4_3psu/",
    modelName: "S4_3GovtPSUSelection",
    FormComponent: S4_3Form,
    listFields: [
      fields.studentNameField,
      { label: "PSU Name", key: "psv_name" },
      { label: "Package", key: "package_offered" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S4.4": {
    endpoint: "api/data/s4_4full/",
    modelName: "S4_4PlacementHigherStudies",
    FormComponent: S4_4Form,
    listFields: [
      fields.studentNameField,
      { label: "Placement Type", key: "placement_type" },
      { label: "Organization", key: "organization_name" },
      { label: "Package", key: "package_offered" },
      { label: "Higher Studies Program", key: "program_name" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S5.1": {
    endpoint: "api/data/s5_1certcourses/",
    modelName: "S5_1StudentCertificationCourse",
    FormComponent: S5_1Form,
    listFields: [
      fields.studentNameField,
      { label: "Course Name", key: "certification_course" },
      { label: "Duration", key: "duration" },
      { label: "Type", key: "certification_type" },
      fields.certificateLinkField,
      fields.departmentNameField,
    ],
  },
  "S5.2": {
    endpoint: "api/data/s5_2vocational/",
    modelName: "S5_2VocationalTraining",
    FormComponent: S5_2Form,
    listFields: [
      fields.studentNameField,
      { label: "Company Name", key: "company_name" },
      { label: "Duration", key: "duration" },
      fields.certificateLinkField,
      fields.departmentNameField,
    ],
  },
  "S5.3": {
    endpoint: "api/data/s5_3special/",
    modelName: "S5_3SpecialMentionAchievement",
    FormComponent: S5_3Form,
    listFields: [
      fields.studentNameField,
      { label: "Award Name", key: "award_name" },
      { label: "Awarding Organization", key: "awarding_organization" },
      { label: "Level", key: "award_level" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
  "S5.4": {
    endpoint: "api/data/s5_4entrepreneurs/",
    modelName: "S5_4StudentEntrepreneurship",
    FormComponent: S5_4Form,
    listFields: [
      fields.studentNameField,
      { label: "Organization", key: "organization_details" },
      { label: "Establishment Year", key: "establishment_year" },
      { label: "Sector", key: "sector" },
      fields.proofLinkField,
      fields.departmentNameField,
    ],
  },
};

