# Generated by Django 5.2.3 on 2025-08-07 11:52
# This is the updated migration file that correctly reflects the models.py.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Faculty', 'Faculty'), ('HOD', 'HOD'), ('Admin', 'Admin')], default='Faculty', max_length=10)),
                # --- V MODIFIED ---
                # Added null=True and blank=True to match the model definition.
                # This allows a Profile to exist without an associated department.
                ('department', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='reports.department'
                )),
                # --- ^ END MODIFIED ---
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='profile',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]