# Generated by Django 5.2.3 on 2025-08-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_s1_1theorysubjectdata_department_and_more'),
        ('users', '0003_profile_middle_name_profile_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.department'),
        ),
    ]
