# Generated by Django 5.2.3 on 2025-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
