# Generated by Django 5.2.3 on 2025-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('HOD', 'HOD'), ('Admin', 'Admin'), ('Student', 'Student')], default='Faculty', max_length=10),
        ),
    ]
